import { Chat } from '@google/genai';

// Declare global variables from CDN scripts to make TypeScript aware of them
// FIX: Wrapped global variable declarations in `declare global {}` to make them available across the entire project.
declare global {
    var PptxGenJS: any;
    var docx: any;
    var ExcelJS: any;
    var QRCode: any;
    var jspdf: any;
}


export type Page = 'home' | 'projects' | 'chat';

export interface FileAttachment {
    name: string;
    base64: string;
    mimeType: string;
}

export interface VirtualFile {
    name: string;
    content: string; // For text files; for binary, could be base64
}

export type CanvasFiles = { [filename: string]: string };

export type MessageSender = 'user' | 'ai';

export interface Source {
    uri: string;
    title: string;
    type: 'web' | 'map';
}

export type MarkdownSegment = 
    | { type: 'paragraph'; content: string }
    | { type: 'code'; language?: string; filename?: string; content: string };

export interface Task {
    id: string;
    description: string;
    completed: boolean;
    createdAt: { seconds: number, nanoseconds: number }; // Firestore timestamp format
}

export type StructuredToolOutput =
    | { type: 'search_results'; results: { title: string; link: string }[] }
    | { type: 'browsed_content'; url: string; content: string }
    | { type: 'text'; content: string }
    | { type: 'plot'; dataUrl: string }
    | { type: 'file_generated'; filename: string; message: string }
    | null;


export interface WorkflowStep {
    summary: string;
    status: 'pending' | 'running' | 'completed' | 'paused_for_approval' | 'error' | 'denied';
    tool_call?: { name: string; args: any; };
    tool_output?: StructuredToolOutput;
}

export interface Workflow {
    goal: string;
    plan: string[]; // The initial plan generated by the agent
    steps: WorkflowStep[];
    status: 'running' | 'completed' | 'error' | 'paused_for_approval' | 'denied';
    finalContent: string | null;
}


export interface Message {
    id:string;
    text: string;
    sender: MessageSender;
    timestamp: Date;
    // FIX: Add 'streaming' to the possible status values to support streaming messages.
    status?: 'sent' | 'read' | 'streaming';
    imageUrls?: string[];
    attachments?: FileAttachment[];
    sources?: Source[];
    weatherData?: WeatherData;
    generatedImage?: {
        prompt: string;
        url?: string;
        aspectRatio?: '1:1' | '16:9' | '9:16' | '4:3' | '3:4';
        isLoading?: boolean;
    };
    editedImage?: {
        beforeUrl: string;
        afterUrl?: string;
        prompt: string;
        isLoading?: boolean;
    };
    generatedVideo?: {
        status: 'generating' | 'completed' | 'error';
        url?: string;
        prompt: string;
    };
    segments?: MarkdownSegment[]; // For rendering mixed content
    requiresAction?: 'nsfw_confirmation' | 'open_mailto' | 'workflow_confirmation';
    actionData?: any; // To store data needed for an action, e.g., the mailto URL
    actionTaken?: boolean;
    tasks?: Task[]; // For displaying a list of tasks
    workflow?: Workflow;
    audioUrl?: string;
    storyboardImages?: { prompt: string; url: string }[]; // For storyboard feature
    sessionFiles?: VirtualFile[]; // For Code Interpreter
    codeExecutionResult?: {
        code: string;
        output: string;
    };
    generatedFile?: {
        filename: string;
        message: string;
        data?: PresentationData | WordData | ExcelData;
        type?: 'pptx' | 'docx' | 'xlsx' | 'pdf';
        previewImageUrl?: string; // For PPTX preview
        isPreviewLoading?: boolean; // To show a shimmer/loader
    };
    generatedQRCode?: {
        text: string;
        dataUrl: string;
    };
}


export interface WeatherData {
    city: string;
    country: string;

    temperature: string;
    description: string;
    icon?: string;
}

export interface NavigationProps {
    navigateTo: (page: Page) => void;
}

export interface ChatListItem {
    id: string;
    title: string;
    createdAt: { seconds: number; nanoseconds: number; };
}

export interface UserProfile {
    uid: string; // Will now be the username
    displayName: string | null;
    email: string | null;
    photoURL: string | null;
    customInstructions?: string;
    aboutYou?: string; // How the AI should refer to the user
    onboardingCompleted?: boolean;
    pin: string;
}

export interface Persona {
    name: string;
    icon: string;
    systemInstruction: string;
    description: string;
    isCustom?: boolean;
}

// Data structures for file generation
export interface SlideData {
    title: string;
    content: string[]; // bullet points
    speakerNotes?: string;
}
export interface PresentationData {
    slides: SlideData[];
}

export interface DocumentSection {
    title: string;
    content: string;
}
export interface WordData {
    title: string;
    sections: DocumentSection[];
}

export interface ExcelData {
    filename: string;
    sheets: {
        sheetName: string;
        headers: string[];
        rows: (string | number)[][];
    }[];
}